/* Generated by Yosys 0.33+6 (git sha1 05f0262d775, gcc 13.2.1 -O2 -fexceptions -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -Os) */

module asyncres(clk, d, ares, q);
  reg \$auto$verilog_backend.cc:2184:dump_module$2  = 0;
  reg _0_;
  input ares;
  wire ares;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  reg q;
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$2 ) begin end
    _0_ = q;
    casez (ares)
      1'h1:
          _0_ = 1'h0;
      default:
          _0_ = d;
    endcase
  end
  always @(posedge clk) begin
      q <= _0_;
  end
  always @(posedge ares) begin
      q <= _0_;
  end
endmodule
