/* Generated by Yosys 0.32+1 (git sha1 389b8d0f94a, gcc 13.2.1 -O2 -fexceptions -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -Os) */

module mux(i0, i1, s, y);
  input i0;
  wire i0;
  input i1;
  wire i1;
  input s;
  wire s;
  output y;
  wire y;
  assign y = s ? i1 : i0;
endmodule
